# Generated by Django 4.1 on 2022-11-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0007_job_delivered_at_job_delivery_photo_job_pickedup_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_at'], name='shipping_jo_created_804318_idx'),
        ),
    ]
